import ProjectDescription

public struct CFWorkspace {

    public let name: Name
    public let projectPaths: [CFFilePath]
    public let xcodeVersion: Version

    public init(
        name: Name,
        projectPaths: [CFFilePath],
        xcodeVersion: Version
    ) {
        self.name = name
        self.projectPaths = projectPaths
        self.xcodeVersion = xcodeVersion
    }

}

public extension CFWorkspace {
    
    static func `default`(
        name: Name,
        xcodeVersion: Version
    ) -> Self {
        CFWorkspace(
            name: name,
            projectPaths: ["."],
            xcodeVersion: xcodeVersion
        )
    }

}

public extension CFWorkspace {

    func toTuist() -> Workspace {
        Workspace(
            name: name.toTuist(),
            projects: projectPaths.map { .path($0.toTuist()) },
            schemes: [],
            fileHeaderTemplate: .string(""),
            generationOptions: .options(
                enableAutomaticXcodeSchemes: false,
                autogeneratedWorkspaceSchemes: .enabled(
                    codeCoverageMode: .relevant
                ),
                lastXcodeUpgradeCheck: xcodeVersion
            )
        )
    }

}
